### ISSUE TITLE
Upgrade yard to version 0.9.11 or later

### ISSUE THREAD

**Issue by emma5678** [shiftcommerce/penthouse#13]
yard vulnerability has been present in penthouse.gemspec since Dec 2017. We need to upgrade to 0.9.11 or later.

This needs to be complete by April 2019.

Due to time passed, I would suggest updating to the very latest version, if greater than 0.9.11, unless an issue is identified with doing so.

Vulnerability details:

lib/yard/core_ext/file.rb in the server in YARD before 0.9.11 does not block relative paths with an initial ../ sequence, which allows attackers to conduct directory traversal attacks and read arbitrary files.

**Comment by emma5678** [comment]
@ryantownsend @krisquigley can this be addressed please.

**Comment by emma5678** [comment]
@ryantownsend @krisquigley can this ticket be prioritised please

**Comment by simonireilly** [comment]
Closed by #16 we no longer have a `Gemfile.lock` version pinning yard. The security dependency management is now in the vendor installing the gem.
